# Generated by Django 4.1.5 on 2023-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile')),
                ('date', models.DateField(blank=True, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('adhar_no', models.IntegerField()),
                ('dob', models.DateField(blank=True)),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('dist', models.IntegerField()),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('gujrat', 'Gujrat'), ('Rajasthan', 'Rajasthan')], max_length=50)),
                ('physical', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('schoolname', models.CharField(max_length=50)),
            ],
        ),
    ]
