# Generated by Django 4.0.4 on 2023-01-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile')),
                ('date', models.DateField()),
                ('surname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('adhar_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('dist', models.IntegerField()),
                ('state', models.CharField(choices=[('mh', 'Maharashtra'), ('gj', 'Gujrat'), ('Rj', 'Rajasthan')], max_length=50)),
                ('physical', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=50)),
                ('schoolname', models.CharField(max_length=50)),
            ],
        ),
    ]
