# Generated by Django 4.0.4 on 2023-01-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
