# Generated by Django 4.1.5 on 2023-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_applicationform_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
    ]
