# Generated by Django 4.1.5 on 2023-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_applicationform_name_alter_applicationform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='physical',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='state',
            field=models.CharField(choices=[('maharashtra', 'Maharashtra'), ('gujrat', 'Gujrat'), ('Rajasthan', 'Rajasthan')], max_length=50),
        ),
    ]
